#!/bin/bash
#
# Author: Pierre Visconti
# Lightfetch: a lightweight command-line fetcher to display system stats
# 
# Some pieces of code were taken from the following projects (definitely check them out):
# Fetch: https://github.com/Manas140/fetch
# Neofetch: https://github.com/dylanaraps/neofetch
#
#
# Default config file, named "lightfetch" is located in /usr/locale/bin
# To run a modified file, copy the default one and place the copy in ~/.config/lightfetch
# 	Then pass the filename as an argument:
#	Ex: lightfetch -c mytheme
# Typing lightfetch without passing an argument will run the default config 
#	Ex: lightfetch

set -euo pipefail


function main {	
	### Possible colors have been defined below
	# prefixes:
	# l: light variant
	# d: dark variant
	# b: bolded
	local default="\e[0;39m"
	local black="\e[0;30m"
	local red="\e[0;31m"
	local green="\e[0;32m"
	local yellow="\e[0;33m"
	local blue="\e[0;34m"
	local purple="\e[0;35m"
	local cyan="\e[0;36m"
	local l_gray="\e[0;37m"
	local d_gray="\e[0;90m"
	local l_red="\e[0;91m"
	local l_green="\e[0;92m"
	local l_yellow="\e[0;93m"
	local l_blue="\e[0;94m"
	local l_purple="\e[0;95m"
	local l_cyan="\e[0;96m"
	local white="\e[0;97m"
	local b_default="\e[1;39m"
	local b_black="\e[1;30m"
	local b_red="\e[1;31m"
	local b_green="\e[1;32m"
	local b_yellow="\e[1;33m"
	local b_blue="\e[1;34m"
	local b_purple="\e[1;35m"
	local b_cyan="\e[1;36m"
	local bl_gray="\e[1;37m"
	local bd_gray="\e[1;90m"
	local bl_red="\e[1;91m"
	local bl_green="\e[1;92m"
	local bl_yellow="\e[1;93m"
	local bl_blue="\e[1;94m"
	local bl_purple="\e[1;95m"
	local bl_cyan="\e[1;96m"
	local b_white="\e[1;97m"

	
	######## CUSTOMIZATION VARIABLES: MODIFY THE FOLLOWING SECTION #############
	# Distro name settings
	os_name_full="TRUE" # set to "TRUE" if you wish to display the full name
	# Shell settings
	shell_full="TRUE" # set to "TRUE" if you wish to display the full path
	# Memory settings:
	memory_disp_units="TRUE" # set to "TRUE" if you wish to display the units
	memory_units_type="M" # set to "M" for MB, set to "G" for GB, default units are kB (Note: kB=1024 bytes)
	memory_units_scaling="2" # sets number of digits after decimal point (only relevant for GB unit type)
	# CPU settings
	cpu_brand="TRUE" # set to TRUE if you wish to display CPU brand name
	cpu_disp_units="TRUE" # set to "TRUE" if you wish to display the units
	cpu_units_type="G" # set to "G" for GHz, default units are in MHz
	cpu_units_scaling="1" # sets number of digits after decimal point (only relevant for GHz unit type)
	cpu_core_count="L" # set to "L" to display logical cores, default is physical cores

	##################### END OF CUSTOMIZATION VARIABLES #######################


	### Display variables have been defined below
	# User and hostname
	local title=$(Title)
	# distro name
	local os_name=$(OS_Name)
	# kernel version
	local kernel=$(Kernel)
	# Desktop environment / window manager
	local de_wm=$(Desktop)
	# system shell 
	local shell=$(Shell)
	# system uptime
	local uptime=$(Uptime)
	# system uptime but saved as seperate variables for each unit of time (must be used together)
	local uptime_d=$(Uptime_D) # days
	local uptime_h=$(Uptime_H) # hours
	local uptime_m=$(Uptime_M) # minutes
	# Used and available memory  
	local memory=$(Memory)
	# cpu model name
	local cpu_model=$(CPU_Model)
	# cpu information:
	local cpu_speed=$(CPU_Speed) 
	local cpu_cores=$(CPU_Cores)
	local cpu_temp=$(CPU_Temp)

	########### OUTPUT: MODIFY THE FOLLOWING SECTION ###############
	echo ""
	echo -e "   ${default}-----------------------------------------"
	printf "        ${b_blue}${title}\n\n"
	printf "        ${b_blue}OS      ${default}: ${os_name}\n"
	printf "        ${b_blue}Kernel  ${default}: ${kernel}\n"		
	printf "        ${b_blue}DE/WM   ${default}: ${de_wm}\n"
	printf "        ${b_blue}Shell   ${default}: ${shell}\n"
	printf "        ${b_blue}Uptime  ${default}: ${uptime_d} days, ${uptime_h} hours, ${uptime_m} mins\n"
	printf "        ${b_blue}Memory  ${default}: ${memory}\n"
	printf "        ${b_blue}CPU     ${default}: ${cpu_model} (${cpu_cores}) ${cpu_speed} ${cpu_temp}\n"
	echo -e "   ${default}-----------------------------------------"
	echo ""
	##################### END OF OUTPUT ############################
}

function Title {
	local hostname=$(cat /etc/hostname)
	printf "${USER}@${hostname}"
}

function OS_Name {
	if [ "${os_name_full}" == "TRUE" ]; then
		local os_name=$(grep "\<PRETTY_NAME\>" /etc/os-release)
		if [ "${os_name}" ]; then
			os_name="${os_name%\"*}"
			os_name="${os_name#*\"}"
			printf "${os_name}"
		fi
	else 
		local os_name=$(grep "\<NAME\>" /etc/os-release)
		os_name="${os_name%\"*}"
		os_name="${os_name#*\"}"
		printf "${os_name}"
	fi
}

function Kernel {
	local kern=
	read -r _ _ kern _ < /proc/version
	printf "$kern"
}

function Desktop {
	if [ "${DESKTOP_SESSION}" != "" ]; then
	printf "${DESKTOP_SESSION}"
	elif [ "${XDG_CURRENT_DESKTOP}" != "" ]; then
	printf "${XDG_CURRENT_DESKTOP}"
	else
	for i in /proc/*/comm; do
		local p=
		read -r p < "$i"
		case "$p" in
		awesome|xmonad*|qtile|sway|i3|[bfo]*box|*wm*) printf "${p%%-*}"; break;;
		esac
	done
	fi
}

function Shell {
	if [ "${shell_full}" == "TRUE" ]; then
		printf "${SHELL}"
	else
		printf "${SHELL##*/}"
	fi
}

function Uptime {
	local up=
	IFS=. read -r up _ < /proc/uptime
	local day=$((up / 60 / 60 / 24))
	local hr=$((up / 60 / 60 % 24))
	local min=$((up / 60 % 60))
	printf "%dd %dh %dm" "${day}" "${hr}" "${min}"
}

function Uptime_D {
	local up=
	IFS=. read -r up _ < /proc/uptime
	local day=$((up / 60 / 60 / 24))
	printf "${day}"
}

function Uptime_H {
	local up=
	IFS=. read -r up _ < /proc/uptime
	local hr=$((up / 60 / 60 % 24))
	printf "${hr}"
}

function Uptime_M {
	local up=
	IFS=. read -r up _ < /proc/uptime
	local min=$((up / 60 % 60))
	printf "${min}"
}

function Memory {
	local mem_used=
	local mem_total=
	local a=
	local b=
	while IFS=":" read -r a b; do
	case $a in
        	"MemTotal") ((mem_used+=${b/kB})); mem_total="${b/kB}" ;;
        	"Shmem") ((mem_used+=${b/kB}))  ;;
        	"MemFree" | "Buffers" | "Cached" | "SReclaimable")
        	mem_used="$((mem_used-=${b/kB}))"
        	;;
    	esac
  	done < /proc/meminfo
	
	if [ "${memory_units_type}" == "M" ]; then
		mem_used="$(( mem_used / 1024 ))"
  		mem_total="$(( mem_total / 1024 ))"
		if [ "${memory_disp_units}" == "TRUE" ]; then
			printf "${mem_used}MB / ${mem_total}MB"
		else 
			printf "${mem_used} / ${mem_total}"
		fi
	elif [ "${memory_units_type}" == "G" ]; then
		mem_used=$(echo "scale = ${memory_units_scaling}; $mem_used / 1048576" | bc)
  		mem_total=$(echo "scale = ${memory_units_scaling}; $mem_total / 1048576" | bc )
		if [ "${memory_disp_units}" == "TRUE" ]; then
			printf "${mem_used}GB / ${mem_total}GB"
		else 
			printf "${mem_used} / ${mem_total}"
		fi
	else 
		mem_used="${mem_used// /}"
		mem_total="${mem_total// /}"
		if [ "${memory_disp_units}" == "TRUE" ]; then
			printf "${mem_used}kB / ${mem_total}kB"
		else 
			printf "${mem_used} / ${mem_total}"
		fi
	fi
}

function CPU_Model {
	local cpu=$(grep -m 1 "model name" /proc/cpuinfo)
	cpu="${cpu%\@*}"
	cpu="${cpu#*\:}"
	# Remove un-needed patterns from cpu output.
	cpu="${cpu//(TM)}"
	cpu="${cpu//(tm)}"
	cpu="${cpu//(R)}"
	cpu="${cpu//(r)}"
	cpu="${cpu//CPU}"
	cpu="${cpu//Processor}"
	cpu="${cpu//Dual-Core}"
	cpu="${cpu//Quad-Core}"
	cpu="${cpu//Six-Core}"
	cpu="${cpu//Eight-Core}"
	cpu="${cpu//[1-9][0-9]-Core}"
	cpu="${cpu//[0-9]-Core}"
	cpu="${cpu//, * Compute Cores}"
	cpu="${cpu//Core / }"
	cpu="${cpu//(\"AuthenticAMD\"*)}"
	cpu="${cpu//with Radeon * Graphics}"
	cpu="${cpu//, altivec supported}"
	cpu="${cpu//FPU*}"
	cpu="${cpu//Chip Revision*}"
	cpu="${cpu//Technologies, Inc}"
	cpu="${cpu//Core2/Core 2}"
	shopt -s extglob
	cpu="${cpu##+([[:space:]])}"
	cpu="${cpu%%+([[:space:]])}"
	local cpu_n="${cpu#*\ }"		
	cpu_n="${cpu_n##+([[:space:]])}"
	local cpu_e="${cpu_n#*\ }"
	cpu_e="${cpu_e// /}"
	cpu_n="${cpu_n%\ *}"
	cpu_n="${cpu_n// /}"
	local cpu_b=$(echo $cpu)
	if [ "$cpu_brand" == "TRUE" ]; then
		printf "${cpu_b}"
	else
		if [ "${cpu_n}" == "${cpu_e}" ]; then
			printf "${cpu_n}"
		else
			printf "${cpu_n} ${cpu_e}"
		fi
	fi
}

function CPU_Speed {
	local speed_dir="/sys/devices/system/cpu/cpu0/cpufreq"
	local speed=
	# Get CPU speed.
	if [ -d "$speed_dir" ]; then
		if [ -f "${speed_dir}/bios_limit" ]; then 
			speed=$(cat "${speed_dir}/bios_limit")
		elif [ -f "${speed_dir}"/scaling_max_freq ]; then
			speed=$(cat "${speed_dir}/scaling_max_freq")
		else
			speed=$(cat "${speed_dir}/cpuinfo_max_freq")
		fi
		speed=$((speed / 1000))
	else
		speed=$(grep -m 1 "cpu MHz" /proc/cpuinfo)
		speed="${speed#*:}"
		speed="${speed%.*}"
		speed="${speed// /}"

	fi
	# Print speed as GHz or MHz dependng on cpu_units_type
	if [ "${cpu_units_type}" == "G" ]; then
		speed=$(echo "scale = ${cpu_units_scaling}; $speed / 1000" | bc)
		if [ "${cpu_disp_units}" == "TRUE" ]; then
			printf "${speed}GHz"
		else 
			printf "${speed}"
		fi
	else 
		if [ "${cpu_disp_units}" == "TRUE" ]; then
			printf "${speed}MHz"
		else 
			printf "${speed}"
		fi
	fi
}

function CPU_Cores {
	# Get CPU cores.
	local core_count=
	if [ "${cpu_core_count}" == "L" ]; then
		core_count=$(grep -c processor /proc/cpuinfo)
		printf "${core_count}"
	else
		core_count=$(grep "core id" /proc/cpuinfo | tail -1) 
		core_count="${core_count#*:}"
		core_count="${core_count// /}"
		core_count=$((core_count + 1))
		printf "${core_count}"
	fi
}

function CPU_Temp {
	# Select the right temperature file.
	for temp_dir in /sys/class/hwmon/*; do
		[[ "$(< "${temp_dir}/name")" =~ (coretemp|fam15h_power|k10temp) ]] && {
			temp_dirs=("$temp_dir"/temp*_input)
			temp_dir=${temp_dirs[0]}
			break
		}
	done

	# Get CPU temp.
	[[ -f "$temp_dir" ]] && deg=$(echo "scale = 1; $(< "$temp_dir") / 1000" | bc)
	printf "${deg}°"
}

function Help { 
	printf "\n Usage: lightfetch [ -c file_name | -h ]
	-c: provide a filename in ~/.config/lightfetch  
	-h: help
	: default configuration \n\n"
}

### Runs lightfetch based on user input
set +u
if [ "${1}" ]; then
	case "${1}" in
  		*-c*) 
			if [ "$2" ]; then
				if [ -f "${HOME}"/.config/lightfetch/"${2}" ]; then
		 			"${HOME}"/.config/lightfetch/"${2}" 
				fi
			fi;;
  		*-h*) Help;;
	esac
else 
	main "$@"
fi

